import { ROLES_ENUM } from "./roles.enum";




export const RESOURCE_BY_ROLES = {
    
    
    /*Resumen*/RESUMEN_OPTION:[ROLES_ENUM.TEST],
    /*Reportes*/REPORT_OPTION:[ROLES_ENUM.TEST,ROLES_ENUM.PREMIUM,ROLES_ENUM.PREMIUMHOTEL],
    /*Mis gastos/retiros*/EXPENSES_OPTION: [ROLES_ENUM.TEST],
    /*Movimiento dinero*/ MOVES_OPTION:[ROLES_ENUM.NORMAL ,ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Mis clientes*/  CLIENTS_OPTION:[ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES,ROLES_ENUM.PREMIUMHOTEL,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.SALESHOTEL],
    /*Necesito ayuda*/     NEED_HELP:[ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES,ROLES_ENUM.SALESHOTEL,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Mis productos*/PRODUCTS_OPTION : [ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Mi catálogo web*/CATALOG_OPTION:  [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES],
    /*Mis proveedores*/SUPPLIER_OPTION:[ROLES_ENUM.TEST ],
    /*Utilidad*/ BALANCE_OPTION: [ROLES_ENUM.TEST,ROLES_ENUM.NORMAL,ROLES_ENUM.PREMIUM],
    /*Configuraciones*/SETTINGS_OPTION:  [ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.PREMIUMHOTEL],
    /*Cambiar contraseña */ CHANGE_PASSWORD:[ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.SALESHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Asesor digital*/ ADVISER_OPTION:[ ROLES_ENUM.TEST],
    /*Alerta stock*/ALERT_OPTION:[ROLES_ENUM.TEST,ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.MANAGER,ROLES_ENUM.PREMIUMHOTEL,ROLES_ENUM.MANAGERHOTEL],
    /*Asociar cuenta*/  ADD_USER:[ROLES_ENUM.TEST,ROLES_ENUM.PREMIUM,ROLES_ENUM.PREMIUMHOTEL],
    /**/BOOKS:[ROLES_ENUM.TEST,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.SALESHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /**/OFFERTS:[ROLES_ENUM.TEST],
    /**/MY_ROOMS:[ROLES_ENUM.TEST,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Cerrar Sesión*/CLOSE_SESSION:[ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.SALESHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /*Vender y pedidos*/VENDER_OPTION:            [ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.SALESHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    /**/PRODUCT_REGISTER_OPTION:[ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.MANAGERHOTEL,ROLES_ENUM.PREMIUMHOTEL],
    INFORMATION_OPTION:[ROLES_ENUM.TEST],
    RESTAURANT: [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM, ROLES_ENUM.TEST, ROLES_ENUM.MANAGER, ROLES_ENUM.COCINERO, ROLES_ENUM.MOZO],
    AREAKITCHEN: [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM, ROLES_ENUM.TEST, ROLES_ENUM.MANAGER, ROLES_ENUM.COCINERO, ROLES_ENUM.MOZO],
   
    /*ORDERS_OPTION:            [ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER,ROLES_ENUM.SALES],*/
    
    /*GOALS_OPTION:            [ROLES_ENUM.NORMAL , ROLES_ENUM.PREMIUM,ROLES_ENUM.TEST,ROLES_ENUM.MANAGER],*/
    //BALANCE_OPTION:            [ROLES_ENUM.TEST],

    /**/AREAS: [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM, ROLES_ENUM.TEST, ROLES_ENUM.MANAGER, ROLES_ENUM.COCINERO, ROLES_ENUM.MOZO],
    /**/ZONAS: [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM, ROLES_ENUM.TEST, ROLES_ENUM.MANAGER, ROLES_ENUM.COCINERO, ROLES_ENUM.MOZO],
    DISHREGISTER: [ROLES_ENUM.NORMAL, ROLES_ENUM.PREMIUM, ROLES_ENUM.TEST, ROLES_ENUM.MANAGER, ROLES_ENUM.COCINERO, ROLES_ENUM.MOZO],

   
}