export enum ROLES_ENUM{
    PREMIUM="PREMIUM",
    PREMIUMHOTEL="PREMIUMHOTEL",
    NORMAL="NORMAL",
    TEST="TEST",
    ENTERPRICE="ENTERPRICE",
    SALES="SALES",
    MANAGER="MANAGER",
    MANAGERHOTEL="MANAGERHOTEL",
    SALESHOTEL="SALESHOTEL",

    
    COCINERO="COCINERO",
    MOZO="MOZO"
    
}